name: sr4s_env
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy<2
  - pillow
  - rasterio
  - scikit-image
  - requests
  - sentinelhub
  - ipykernel
  - pip:
      - opencv-python<4.12
      - safetensors
      - torch
      - torchvision
