name: sr4s_env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - expat=2.7.1
  - libcxx=19.1.7
  - libffi=3.4.4
  - ncurses=6.5
  - openssl=3.0.17
  - pip=25.1
  - python=3.12.11
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - aenum==3.1.16
      - affine==2.4.0
      - attrs==25.3.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - dataclasses-json==0.6.7
      - dotenv==0.9.9
      - filelock==3.19.1
      - fsspec==2025.7.0
      - idna==3.10
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - mpmath==1.3.0
      - mypy-extensions==1.1.0
      - networkx==3.5
      - numpy==2.2.6
      - oauthlib==3.3.1
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pillow==11.3.0
      - pyparsing==3.2.3
      - pyproj==3.7.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - rasterio==1.4.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - sentinelhub==3.11.1
      - shapely==2.1.1
      - six==1.17.0
      - sympy==1.14.0
      - tifffile==2025.8.28
      - tomli==2.2.1
      - tomli-w==1.2.0
      - torch==2.2.2
      - torchvision==0.17.2
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - urllib3==2.5.0
      - utm==0.8.1